### ISSUE TITLE
可以增加更新源吗？

### ISSUE THREAD

**Issue by Roiyaru** [SuperNG6/Aria2-Trackers#1]
项目主，你好。我找到了另外几个更新源（部分重复），可以把整合这些更新源吗？感谢。
https://newtrackon.com/list
https://torrents.io/tracker-list
https://gitee.com/banbendalao/hosts_optimize_tracker_links/raw/master/tracker.txt

**Comment by SuperNG6** [comment]
其实没有必要，trackers的作用没有想像那么大，一般种子和磁链都包含了，重要的是DHT和端口开放
可以参考一下我这个项目
https://github.com/SuperNG6/docker_aria2

**Comment by Roiyaru** [comment]
OK，
